inputs="
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_DYJetsToQQ_analysis_double_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_DYJetsToQQ_analysis_single_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_QCD_HT1000to1500_analysis_double_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_QCD_HT1000to1500_analysis_single_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_QCD_HT100to200_analysis_double_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_QCD_HT100to200_analysis_single_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_QCD_HT1500to2000_analysis_double_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_QCD_HT1500to2000_analysis_single_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_QCD_HT2000toInf_analysis_double_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_QCD_HT2000toInf_analysis_single_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_QCD_HT200to300_analysis_double_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_QCD_HT200to300_analysis_single_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_QCD_HT300to500_analysis_double_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_QCD_HT300to500_analysis_single_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_QCD_HT500to700_analysis_double_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_QCD_HT500to700_analysis_single_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_QCD_HT700to1000_analysis_double_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_QCD_HT700to1000_analysis_single_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_ST_s-channel_analysis_double_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_ST_s-channel_analysis_single_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_ST_s_inclusive_analysis_double_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_ST_s_inclusive_analysis_single_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_ST_t-channel_antitop_4f_inclusiveDecays_analysis_double_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_ST_t-channel_antitop_4f_inclusiveDecays_analysis_single_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_ST_t-channel_top_4f_inclusiveDecays_analysis_double_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_ST_t-channel_top_4f_inclusiveDecays_analysis_single_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_ST_tW_antitop_analysis_double_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_ST_tW_antitop_analysis_single_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_ST_tW_top_analysis_double_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_ST_tW_top_analysis_single_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_TT_analysis_double_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_TT_analysis_single_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_WJetsToQQ_analysis_double_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_WJetsToQQ_analysis_single_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_WW_analysis_double_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_WW_analysis_single_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_WZ_analysis_double_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_WZ_analysis_single_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_WminusH_HToBB_analysis_double_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_WminusH_HToBB_analysis_single_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_WplusH_HToBB_analysis_double_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_WplusH_HToBB_analysis_single_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_ZH_HToBB_analysis_double_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_ZH_HToBB_analysis_single_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_ZZ_analysis_double_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_ZZ_analysis_single_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_bbHToBB_yb2_analysis_double_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_bbHToBB_yb2_analysis_single_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_bbHToBB_ybyt_analysis_double_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_bbHToBB_ybyt_analysis_single_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_ttHToNonbb_M125_analysis_double_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_ttHToNonbb_M125_analysis_single_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_ttHTobb_M125_analysis_double_trignone_v25_VBF_newReg.root
/afs/cern.ch/work/n/nchernya/VBFHbb_2016/VBF_combine/inputs/root/FitVBF_ttHTobb_M125_analysis_single_trignone_v25_VBF_newReg.root
"

for arg in $inputs
do
	echo -e  ${arg},"\c"
done
